// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJohEv2HvPk4_L6cqIzHonfuNBowlZKuA',
    appId: '1:416599844773:web:104e37f3af99a733832a4c',
    messagingSenderId: '416599844773',
    projectId: 'fluttertest-3d338',
    authDomain: 'fluttertest-3d338.firebaseapp.com',
    storageBucket: 'fluttertest-3d338.firebasestorage.app',
    measurementId: 'G-LDNJBKHTCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDief8CpfgjSwDnP0utan59Upoe5LQicaY',
    appId: '1:416599844773:android:866bf0ba7bfb7f4f832a4c',
    messagingSenderId: '416599844773',
    projectId: 'fluttertest-3d338',
    storageBucket: 'fluttertest-3d338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMAXgScQoWCB9N0ZLe-LffTzOko8CIP0Q',
    appId: '1:416599844773:ios:4179e2a57a223569832a4c',
    messagingSenderId: '416599844773',
    projectId: 'fluttertest-3d338',
    storageBucket: 'fluttertest-3d338.firebasestorage.app',
    iosBundleId: 'com.example.workflow',
  );
}
